[[docs]]
  name = "Prologue"
  weight = 10
  identifier = "prologue"
  url = "https://docs.invidious.io/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "https://docs.invidious.io/"

[[main]]
  name = "Docs"
  url = "https://docs.invidious.io/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
